name: PHP Tests and Linters

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses  : actions/checkout@v3

      - name: Setup PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        run: composer test:ci
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run linters
        run: |
          composer ide-helper
          composer lint
          composer quality
          composer quality:static
