name: PHP Tests and Linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-tests-and-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: Run tests
        run: composer test:ci

      - name: Run linters
        run: |
          composer lint
          composer quality
          composer quality:static
