name: PHP Tests and Linters

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: Run tests
        run: composer test:ci
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: Run linters
        run: |
          composer lint
          composer quality
          composer quality:static
